// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	crit "github.com/b87/go-crit/crit"
	mock "github.com/stretchr/testify/mock"
)

// QueryBuilder is an autogenerated mock type for the QueryBuilder type
type QueryBuilder[Q any] struct {
	mock.Mock
}

type QueryBuilder_Expecter[Q any] struct {
	mock *mock.Mock
}

func (_m *QueryBuilder[Q]) EXPECT() *QueryBuilder_Expecter[Q] {
	return &QueryBuilder_Expecter[Q]{mock: &_m.Mock}
}

// BuildQuery provides a mock function with given fields: criteria
func (_m *QueryBuilder[Q]) BuildQuery(criteria *crit.Criteria) (Q, error) {
	ret := _m.Called(criteria)

	if len(ret) == 0 {
		panic("no return value specified for BuildQuery")
	}

	var r0 Q
	var r1 error
	if rf, ok := ret.Get(0).(func(*crit.Criteria) (Q, error)); ok {
		return rf(criteria)
	}
	if rf, ok := ret.Get(0).(func(*crit.Criteria) Q); ok {
		r0 = rf(criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Q)
		}
	}

	if rf, ok := ret.Get(1).(func(*crit.Criteria) error); ok {
		r1 = rf(criteria)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// QueryBuilder_BuildQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildQuery'
type QueryBuilder_BuildQuery_Call[Q any] struct {
	*mock.Call
}

// BuildQuery is a helper method to define mock.On call
//   - criteria *crit.Criteria
func (_e *QueryBuilder_Expecter[Q]) BuildQuery(criteria interface{}) *QueryBuilder_BuildQuery_Call[Q] {
	return &QueryBuilder_BuildQuery_Call[Q]{Call: _e.mock.On("BuildQuery", criteria)}
}

func (_c *QueryBuilder_BuildQuery_Call[Q]) Run(run func(criteria *crit.Criteria)) *QueryBuilder_BuildQuery_Call[Q] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*crit.Criteria))
	})
	return _c
}

func (_c *QueryBuilder_BuildQuery_Call[Q]) Return(_a0 Q, _a1 error) *QueryBuilder_BuildQuery_Call[Q] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *QueryBuilder_BuildQuery_Call[Q]) RunAndReturn(run func(*crit.Criteria) (Q, error)) *QueryBuilder_BuildQuery_Call[Q] {
	_c.Call.Return(run)
	return _c
}

// NewQueryBuilder creates a new instance of QueryBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryBuilder[Q any](t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryBuilder[Q] {
	mock := &QueryBuilder[Q]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
