// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	crit "github.com/b87/go-crit/crit"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository[E any, M any, Q any] struct {
	mock.Mock
}

type Repository_Expecter[E any, M any, Q any] struct {
	mock *mock.Mock
}

func (_m *Repository[E, M, Q]) EXPECT() *Repository_Expecter[E, M, Q] {
	return &Repository_Expecter[E, M, Q]{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, criteria
func (_m *Repository[E, M, Q]) Find(ctx context.Context, criteria *crit.Criteria) ([]M, int64, error) {
	ret := _m.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []M
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *crit.Criteria) ([]M, int64, error)); ok {
		return rf(ctx, criteria)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *crit.Criteria) []M); ok {
		r0 = rf(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]M)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *crit.Criteria) int64); ok {
		r1 = rf(ctx, criteria)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *crit.Criteria) error); ok {
		r2 = rf(ctx, criteria)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Repository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type Repository_Find_Call[E any, M any, Q any] struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria *crit.Criteria
func (_e *Repository_Expecter[E, M, Q]) Find(ctx interface{}, criteria interface{}) *Repository_Find_Call[E, M, Q] {
	return &Repository_Find_Call[E, M, Q]{Call: _e.mock.On("Find", ctx, criteria)}
}

func (_c *Repository_Find_Call[E, M, Q]) Run(run func(ctx context.Context, criteria *crit.Criteria)) *Repository_Find_Call[E, M, Q] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*crit.Criteria))
	})
	return _c
}

func (_c *Repository_Find_Call[E, M, Q]) Return(_a0 []M, _a1 int64, _a2 error) *Repository_Find_Call[E, M, Q] {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_Find_Call[E, M, Q]) RunAndReturn(run func(context.Context, *crit.Criteria) ([]M, int64, error)) *Repository_Find_Call[E, M, Q] {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository[E any, M any, Q any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository[E, M, Q] {
	mock := &Repository[E, M, Q]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
