// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	crit "github.com/b87/go-crit/crit"
	mock "github.com/stretchr/testify/mock"
)

// CriteriaSort is an autogenerated mock type for the CriteriaSort type
type CriteriaSort[T any] struct {
	mock.Mock
}

type CriteriaSort_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *CriteriaSort[T]) EXPECT() *CriteriaSort_Expecter[T] {
	return &CriteriaSort_Expecter[T]{mock: &_m.Mock}
}

// ToSorts provides a mock function with given fields: obj
func (_m *CriteriaSort[T]) ToSorts(obj T) []crit.Sort {
	ret := _m.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for ToSorts")
	}

	var r0 []crit.Sort
	if rf, ok := ret.Get(0).(func(T) []crit.Sort); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crit.Sort)
		}
	}

	return r0
}

// CriteriaSort_ToSorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSorts'
type CriteriaSort_ToSorts_Call[T any] struct {
	*mock.Call
}

// ToSorts is a helper method to define mock.On call
//   - obj T
func (_e *CriteriaSort_Expecter[T]) ToSorts(obj interface{}) *CriteriaSort_ToSorts_Call[T] {
	return &CriteriaSort_ToSorts_Call[T]{Call: _e.mock.On("ToSorts", obj)}
}

func (_c *CriteriaSort_ToSorts_Call[T]) Run(run func(obj T)) *CriteriaSort_ToSorts_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *CriteriaSort_ToSorts_Call[T]) Return(_a0 []crit.Sort) *CriteriaSort_ToSorts_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CriteriaSort_ToSorts_Call[T]) RunAndReturn(run func(T) []crit.Sort) *CriteriaSort_ToSorts_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewCriteriaSort creates a new instance of CriteriaSort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCriteriaSort[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *CriteriaSort[T] {
	mock := &CriteriaSort[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
