// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// QueryExecutor is an autogenerated mock type for the QueryExecutor type
type QueryExecutor[Q any, E any] struct {
	mock.Mock
}

type QueryExecutor_Expecter[Q any, E any] struct {
	mock *mock.Mock
}

func (_m *QueryExecutor[Q, E]) EXPECT() *QueryExecutor_Expecter[Q, E] {
	return &QueryExecutor_Expecter[Q, E]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, query
func (_m *QueryExecutor[Q, E]) Execute(ctx context.Context, query Q) ([]E, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []E
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, Q) ([]E, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Q) []E); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Q) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, Q) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// QueryExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type QueryExecutor_Execute_Call[Q any, E any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - query Q
func (_e *QueryExecutor_Expecter[Q, E]) Execute(ctx interface{}, query interface{}) *QueryExecutor_Execute_Call[Q, E] {
	return &QueryExecutor_Execute_Call[Q, E]{Call: _e.mock.On("Execute", ctx, query)}
}

func (_c *QueryExecutor_Execute_Call[Q, E]) Run(run func(ctx context.Context, query Q)) *QueryExecutor_Execute_Call[Q, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(Q))
	})
	return _c
}

func (_c *QueryExecutor_Execute_Call[Q, E]) Return(_a0 []E, _a1 int64, _a2 error) *QueryExecutor_Execute_Call[Q, E] {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *QueryExecutor_Execute_Call[Q, E]) RunAndReturn(run func(context.Context, Q) ([]E, int64, error)) *QueryExecutor_Execute_Call[Q, E] {
	_c.Call.Return(run)
	return _c
}

// NewQueryExecutor creates a new instance of QueryExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueryExecutor[Q any, E any](t interface {
	mock.TestingT
	Cleanup(func())
}) *QueryExecutor[Q, E] {
	mock := &QueryExecutor[Q, E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
