// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	crit "github.com/b87/go-crit/crit"
	mock "github.com/stretchr/testify/mock"
)

// CriteriaFilter is an autogenerated mock type for the CriteriaFilter type
type CriteriaFilter[T any] struct {
	mock.Mock
}

type CriteriaFilter_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *CriteriaFilter[T]) EXPECT() *CriteriaFilter_Expecter[T] {
	return &CriteriaFilter_Expecter[T]{mock: &_m.Mock}
}

// ToFilters provides a mock function with given fields: obj
func (_m *CriteriaFilter[T]) ToFilters(obj T) []crit.Filter {
	ret := _m.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for ToFilters")
	}

	var r0 []crit.Filter
	if rf, ok := ret.Get(0).(func(T) []crit.Filter); ok {
		r0 = rf(obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]crit.Filter)
		}
	}

	return r0
}

// CriteriaFilter_ToFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToFilters'
type CriteriaFilter_ToFilters_Call[T any] struct {
	*mock.Call
}

// ToFilters is a helper method to define mock.On call
//   - obj T
func (_e *CriteriaFilter_Expecter[T]) ToFilters(obj interface{}) *CriteriaFilter_ToFilters_Call[T] {
	return &CriteriaFilter_ToFilters_Call[T]{Call: _e.mock.On("ToFilters", obj)}
}

func (_c *CriteriaFilter_ToFilters_Call[T]) Run(run func(obj T)) *CriteriaFilter_ToFilters_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *CriteriaFilter_ToFilters_Call[T]) Return(_a0 []crit.Filter) *CriteriaFilter_ToFilters_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CriteriaFilter_ToFilters_Call[T]) RunAndReturn(run func(T) []crit.Filter) *CriteriaFilter_ToFilters_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewCriteriaFilter creates a new instance of CriteriaFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCriteriaFilter[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *CriteriaFilter[T] {
	mock := &CriteriaFilter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
