// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DataMapper is an autogenerated mock type for the DataMapper type
type DataMapper[E any, M any] struct {
	mock.Mock
}

type DataMapper_Expecter[E any, M any] struct {
	mock *mock.Mock
}

func (_m *DataMapper[E, M]) EXPECT() *DataMapper_Expecter[E, M] {
	return &DataMapper_Expecter[E, M]{mock: &_m.Mock}
}

// MapSingleToEntity provides a mock function with given fields: model
func (_m *DataMapper[E, M]) MapSingleToEntity(model M) E {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for MapSingleToEntity")
	}

	var r0 E
	if rf, ok := ret.Get(0).(func(M) E); ok {
		r0 = rf(model)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(E)
		}
	}

	return r0
}

// DataMapper_MapSingleToEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapSingleToEntity'
type DataMapper_MapSingleToEntity_Call[E any, M any] struct {
	*mock.Call
}

// MapSingleToEntity is a helper method to define mock.On call
//   - model M
func (_e *DataMapper_Expecter[E, M]) MapSingleToEntity(model interface{}) *DataMapper_MapSingleToEntity_Call[E, M] {
	return &DataMapper_MapSingleToEntity_Call[E, M]{Call: _e.mock.On("MapSingleToEntity", model)}
}

func (_c *DataMapper_MapSingleToEntity_Call[E, M]) Run(run func(model M)) *DataMapper_MapSingleToEntity_Call[E, M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(M))
	})
	return _c
}

func (_c *DataMapper_MapSingleToEntity_Call[E, M]) Return(_a0 E) *DataMapper_MapSingleToEntity_Call[E, M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataMapper_MapSingleToEntity_Call[E, M]) RunAndReturn(run func(M) E) *DataMapper_MapSingleToEntity_Call[E, M] {
	_c.Call.Return(run)
	return _c
}

// MapSingleToModel provides a mock function with given fields: entity
func (_m *DataMapper[E, M]) MapSingleToModel(entity E) M {
	ret := _m.Called(entity)

	if len(ret) == 0 {
		panic("no return value specified for MapSingleToModel")
	}

	var r0 M
	if rf, ok := ret.Get(0).(func(E) M); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(M)
		}
	}

	return r0
}

// DataMapper_MapSingleToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapSingleToModel'
type DataMapper_MapSingleToModel_Call[E any, M any] struct {
	*mock.Call
}

// MapSingleToModel is a helper method to define mock.On call
//   - entity E
func (_e *DataMapper_Expecter[E, M]) MapSingleToModel(entity interface{}) *DataMapper_MapSingleToModel_Call[E, M] {
	return &DataMapper_MapSingleToModel_Call[E, M]{Call: _e.mock.On("MapSingleToModel", entity)}
}

func (_c *DataMapper_MapSingleToModel_Call[E, M]) Run(run func(entity E)) *DataMapper_MapSingleToModel_Call[E, M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(E))
	})
	return _c
}

func (_c *DataMapper_MapSingleToModel_Call[E, M]) Return(_a0 M) *DataMapper_MapSingleToModel_Call[E, M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataMapper_MapSingleToModel_Call[E, M]) RunAndReturn(run func(E) M) *DataMapper_MapSingleToModel_Call[E, M] {
	_c.Call.Return(run)
	return _c
}

// MapToEntity provides a mock function with given fields: models
func (_m *DataMapper[E, M]) MapToEntity(models []M) []E {
	ret := _m.Called(models)

	if len(ret) == 0 {
		panic("no return value specified for MapToEntity")
	}

	var r0 []E
	if rf, ok := ret.Get(0).(func([]M) []E); ok {
		r0 = rf(models)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}

	return r0
}

// DataMapper_MapToEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapToEntity'
type DataMapper_MapToEntity_Call[E any, M any] struct {
	*mock.Call
}

// MapToEntity is a helper method to define mock.On call
//   - models []M
func (_e *DataMapper_Expecter[E, M]) MapToEntity(models interface{}) *DataMapper_MapToEntity_Call[E, M] {
	return &DataMapper_MapToEntity_Call[E, M]{Call: _e.mock.On("MapToEntity", models)}
}

func (_c *DataMapper_MapToEntity_Call[E, M]) Run(run func(models []M)) *DataMapper_MapToEntity_Call[E, M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]M))
	})
	return _c
}

func (_c *DataMapper_MapToEntity_Call[E, M]) Return(_a0 []E) *DataMapper_MapToEntity_Call[E, M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataMapper_MapToEntity_Call[E, M]) RunAndReturn(run func([]M) []E) *DataMapper_MapToEntity_Call[E, M] {
	_c.Call.Return(run)
	return _c
}

// MapToModel provides a mock function with given fields: entities
func (_m *DataMapper[E, M]) MapToModel(entities []E) []M {
	ret := _m.Called(entities)

	if len(ret) == 0 {
		panic("no return value specified for MapToModel")
	}

	var r0 []M
	if rf, ok := ret.Get(0).(func([]E) []M); ok {
		r0 = rf(entities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]M)
		}
	}

	return r0
}

// DataMapper_MapToModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapToModel'
type DataMapper_MapToModel_Call[E any, M any] struct {
	*mock.Call
}

// MapToModel is a helper method to define mock.On call
//   - entities []E
func (_e *DataMapper_Expecter[E, M]) MapToModel(entities interface{}) *DataMapper_MapToModel_Call[E, M] {
	return &DataMapper_MapToModel_Call[E, M]{Call: _e.mock.On("MapToModel", entities)}
}

func (_c *DataMapper_MapToModel_Call[E, M]) Run(run func(entities []E)) *DataMapper_MapToModel_Call[E, M] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]E))
	})
	return _c
}

func (_c *DataMapper_MapToModel_Call[E, M]) Return(_a0 []M) *DataMapper_MapToModel_Call[E, M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DataMapper_MapToModel_Call[E, M]) RunAndReturn(run func([]E) []M) *DataMapper_MapToModel_Call[E, M] {
	_c.Call.Return(run)
	return _c
}

// NewDataMapper creates a new instance of DataMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDataMapper[E any, M any](t interface {
	mock.TestingT
	Cleanup(func())
}) *DataMapper[E, M] {
	mock := &DataMapper[E, M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
